routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MasterController@getData')->name('master');
Route::get('/ask', 'MasterController@takeFormQuestion');
Route::post('/question/store', 'MasterController@store');

Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');
Route::group(['prefix' => '/admin/action', 'middleware' => ['auth']], function () {
    Route::get('/', function () {
        return view('admin.home');
    })->name('admin.home');
    Route::resource('/category', 'CategoryController');
    Route::resource('/user', 'UserController');
    Route::resource('/question', 'QuestionController');    
    Route::post('/user/{user}/update', 'UserController@update')->name('user.update');
    Route::get('/category/{category}/questions', 'QuestionController@questions')->name('question.questions');
    Route::get('/category/{category}/unanswered', 'QuestionController@unanswered')->name('unanswered.questions');
    Route::get('/category/{question}/publishHide', 'QuestionController@publishHide')->name('publishHide.questions');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:5|confirmed',
        ]);
        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password'])
        ]);

        return redirect()->route('user.index');
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->name = $request['name'];
        $user->email = $request['email'];
        $user->password = bcrypt($request['password']);
        $user->save();

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('user.index');
    }    
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')
@section('title', 'CategoryCreate')
@section('content')
<h1>Введите данные нового пользователя</h1>
<div class="create_container">
    <form method="POST" action="{{ route('user.store') }}">
        @csrf
        <div class="">
            <div class="">
                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" placeholder="Имя" value="{{ old('name') }}" required autofocus>
                @if ($errors->has('name'))
                    <span class="invalid-feedback">
                        <strong>{{ $errors->first('name') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="">
            <div class="">
                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" placeholder="Email" required>

                @if ($errors->has('email'))
                    <span class="is-invalid">
                        <strong>{{ $errors->first('email') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="">
            <div class="">
                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" placeholder="Пароль" required>

                @if ($errors->has('password'))
                    <span class="is-invalid">
                        <strong>{{ $errors->first('password') }}</strong>
                    </span>
                @endif
            </div>
        </div>
            <div class="">            
                <input id="password-confirm" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password_confirmation" placeholder="Повторите пароль" required>
            </div>
        <div class="">
            <div class="">
                <button type="submit" class="btn btn-primary">
                    Зарегистрировать
                </button>
            </div>
        </div>
    </form>       
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'CategoryCreate')
@section('content')
<h1>Введите новый пароль администратора {{$user->name}}</h1>
<div class="create_container">
    <form method="POST" action="{{ route('user.update', $user) }}">
        {{ csrf_field() }}    
        <input type="password" placeholder="Новый пароль" name="password" required autofocus> 
        <input type="hidden" name="email" required value="{{$user->email}}">
        <input type="hidden" name="name" required value="{{$user->name}}">
        <input type="hidden" name="id" required value="{{$user->id}}">                 
        <button type="submit" class="btn btn-primary btn-block btn-large">Сменить пароль</button>
    </form>    
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Category')
@section('content')
    <h1>Вы просматриваете информацию о существующих администраторах</h1>
    <table class="table">
        <tr>
            <th>№п/п</th>
            <th>Имя администратора</th>  
            <th>Сменить пароль</th>      
            <th>Удалить</th>
        </tr>
        @foreach ($users as $user)
        <tr>
            <td>{{ $loop->iteration }}</td>        
            <td>{{ $user->name }}</td>
            <td><a class="btn btn-primary" href="{{ route('user.edit', $user) }}">Сменить пароль</a></td>         
            <td>            
                <form action="{{ route('user.destroy', $user) }}" method="post">
                    <input class="btn btn-primary" type="submit" value="Удалить администратора">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                </form>
            </td>       
        </tr>    
    @endforeach
    </table>
@endsection
@section('links')
    <a class="admin" href="{{route('user.create')}}">Создать нового администратора</a>
    <a class="admin" href="{{ route('admin.home') }}">Вернуться к списку возможностей администратора</a>
@endsection