routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MasterController@getData')->name('master');
Route::get('/ask', 'MasterController@takeFormQuestion');
Route::post('/question/store', 'MasterController@store');

Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');
Route::group(['prefix' => '/admin/action', 'middleware' => ['auth']], function () {
    Route::get('/', function () {
        return view('admin.home');
    })->name('admin.home');
    Route::resource('/category', 'CategoryController');
    Route::resource('/user', 'UserController');
    Route::resource('/question', 'QuestionController');    
    Route::post('/user/{user}/update', 'UserController@update')->name('user.update');
    Route::get('/category/{category}/questions', 'QuestionController@questions')->name('question.questions');
    Route::get('/category/{category}/unanswered', 'QuestionController@unanswered')->name('unanswered.questions');
    Route::get('/category/{question}/publishHide', 'QuestionController@publishHide')->name('publishHide.questions');
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $fillable = ['question',
        'category_id',
        'author',
        'email_author',
        'status',
        'answer',
        'created_at',
        'updated_at',
    ]; 

    public function category()
    {
        return $this->belongsTo('App\Category');
    }     
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use Illuminate\Http\Request;
use App\Category;

class QuestionController extends Controller
{
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question, Request $request)
    {
        $categories = Category::all();

        return view('admin.questions.edit', compact('question', 'categories'));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        $question->update($request->all());

        return redirect()->route('category.index');          
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $question->delete();

        return back();
    }

    public function questions(Request $request, Category $category)
    {        
        return view('admin.categories.questions', [ 
            'category' => $category,         
            'questions' => $category->question()->paginate(5),            
        ]);        
    }

    public function unanswered(Category $category)
    {        
        return view('admin.questions.unanswered', [ 
            'category' => $category,         
            'questions' => $category->question()->where('answer', NULL)->orderBy('created_at')->paginate(5),
        ]);       
    }

    public function publishHide(Question $question)
    {
        if ($question->status == 0) {
            $newStatus = 1;
        } 
        else {
            $newStatus = 0;
        }
        $question->update([
            'status' => $newStatus,
        ]);
                
        return back();
    }
}

resources/views/admin/questions/edit.blade.php
@extends('admin.layouts.app_form')
@section('title', 'CategoryQuestions')
@section('content')
<h1>Редактируйте вопрос, сколько душе угодно :)</h1>
<form method="post" action="{{ route('question.update', $question) }}">
    {{ method_field('PUT') }}
    {{ csrf_field() }}
    <label id="author">Имя автора вопроса</label>
    <input type="text" name="author" value="{{$question->author}}" required="required" />
    <label id="email">Email автора</label>
    <input type="email" name="email_author" value="{{$question->email_author}}" required="required" />
    <label id="category_id">Тема, к которой вопрос относится</label>
    <select name="category_id">
        @foreach ($categories as $category)
        <option value="{{ $category->id }}" @if($question->category_id == $category->id) selected @endif>{{$category->title}}</option>
        @endforeach
    </select>
    <label id="question">Текст вопроса</label>
    <textarea name="question" required="required">{{$question->question}}</textarea>
    <label id="answer">Текст ответа</label>
    <textarea name="answer" value="{{$question->answer}}" required="required">{{$question->answer}}</textarea>
    <label id="status">Статус вопроса (опубликован или скрыт)</label>
    <select name="status">        
        <option value="1">Опубликовать</option>
        <option value="0">Скрыть</option>        
    </select>
    <button type="submit" class="btn btn-primary btn-block btn-large">Сохранить изменения</button>
</form>
@endsection

resources/views/admin/questions/unanswered.blade.php
@extends('admin.layouts.app')
@section('title', 'CategoryQuestions')
@section('content')
<h1>Вы просматриваете информацию о вопросах без ответа в теме {{$category->title}}</h1>
<table class="table">
    <tr>
        <th>№п/п</th>                
        <th>Дата создания</th>  
        <th>Статус</th>
        <th>Текст вопроса</th>
        <th>Редактировать/Ответить</th>
        <th>Удалить</th>
    </tr>
    @foreach ($questions as $question)
    <tr>
        <td>{{ $loop->iteration }}</td>        
        <td>{{ $question->created_at }}</td>
        <td>
            @if($question->answer == NULL)
                Ожидает ответа
            @elseif($question->status == 0)
                Скрыт
            @else 
                Опубликован            
            @endif
        </td>
        <td>{{$question->question}}</td>
        <td>
            <a class="btn btn-primary" href="{{ route('question.edit', $question) }}">Редактировать/Ответить</a>
        </td>
        <td>
            <form action="{{ route('question.destroy', $question) }}" method="post">
                <input class="btn btn-primary" type="submit" value="Удалить вопрос">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
            </form>
        </td>        
    </tr>    
    @endforeach
</table>
<span>{{$questions->links()}}</span>
<a class="admin" href="{{ route('category.index') }}">Назад к категориям</a>
<a class="admin" href="{{ route('admin.home') }}">Вернуться к списку возможностей администратора</a>
@endsection