routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MasterController@getData')->name('master');
Route::get('/ask', 'MasterController@takeFormQuestion');
Route::post('/question/store', 'MasterController@store');

Auth::routes();

Route::get('/admin', 'HomeController@index')->name('admin');
Route::group(['prefix' => '/admin/action', 'middleware' => ['auth']], function () {
    Route::get('/', function () {
        return view('admin.home');
    })->name('admin.home');
    Route::resource('/category', 'CategoryController');
    Route::resource('/user', 'UserController');
    Route::resource('/question', 'QuestionController');    
    Route::post('/user/{user}/update', 'UserController@update')->name('user.update');
    Route::get('/category/{category}/questions', 'QuestionController@questions')->name('question.questions');
    Route::get('/category/{category}/unanswered', 'QuestionController@unanswered')->name('unanswered.questions');
    Route::get('/category/{question}/publishHide', 'QuestionController@publishHide')->name('publishHide.questions');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Question;

class Category extends Model
{
    public $timestamps = false;
    protected $fillable = ['title'];

    public function question()
    {
        return $this->hasMany('App\Question');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create($request->all());

        return redirect()->route('category.index');
    }    

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        $category->question()->delete();

        return redirect()->route('category.index');
    }

    public function questions(Category $category)
    {
        return view('admin.categories.questions', [ 
            'category' => $category,         
            'questions' => $category->question()->get()->paginate(5),
        ]);        
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('title', 'CategoryCreate')
@section('content')
<h1>Введите название новой темы</h1>
<div class="create_container">
    <form method="POST" action="{{ route('category.store') }}">
        {{ csrf_field() }}    
        <input placeholder="Название темы" name="title" required autofocus>           
        <button type="submit" class="btn btn-primary btn-block btn-large">Создать тему</button>
    </form>    
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Category')
@section('content')
    <h1>Вы просматриваете информацию о существующих темах</h1>
    <table class="table">
        <tr>
            <th>№п/п</th>
            <th>Название темы</th>        
            <th>Всего вопросов</th>  
            <th>Опубликованных вопросов</th>
            <th>Вопросов без ответа</th>
            <th>Просмотреть вопросы</th>
            <th>Удалить</th>
        </tr>
        @foreach ($categories as $category)
        <tr>
            <td>{{ $loop->iteration }}</td>        
            <td>{{ $category->title }}</td>
            <td>{{$category->question()->count()}}</td>
            <td>{{$category->question()->where('status', '!=', 0)->count()}}</td>
            <td>
                {{$category->question()->where('answer', NULL)->count()}}
                <a class="btn btn-primary @if ($category->question()->where('answer', NULL)->count() == 0) hidden @endif" href="{{ route('unanswered.questions', $category) }}">Просмотреть</a> 
            </td> 
            <td> 
                <a class="btn btn-primary" href="{{ route('question.questions', $category) }}">Обзор вопросов</a>            
            </td>   
            <td>            
                <form action="{{ route('category.destroy', $category) }}" method="post">
                    <input class="btn btn-primary" type="submit" value="Удалить тему и все вопросы в ней">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                </form>
            </td>       
        </tr>
        @endforeach
    </table>
@endsection
@section('links')
    <a class="admin" href="{{route('category.create')}}">Создать новую тему</a>
    <a class="admin" href="{{ route('admin.home') }}">Вернуться к списку возможностей администратора</a>
@endsection

resources/views/admin/categories/questions.blade.php
@extends('admin.layouts.app')
@section('title', 'CategoryQuestions')
@section('content')
<h1>Вы просматриваете информацию о вопросах в теме {{$category->title}}</h1>
<table class="table">
    <tr>
        <th>№п/п</th>                
        <th>Дата создания</th>  
        <th>Статус</th>
        <th>Текст вопроса</th>
        <th>Редактировать</th>
        <th>Опубликовать/Скрыть вопрос</th>        
        <th>Удалить</th>
    </tr>
    @foreach ($questions as $question)
    <tr>
        <td>{{$questions->perPage()*($questions->currentPage()-1)+$loop->iteration}}</td>        
        <td>{{ $question->created_at }}</td>
        <td>
            @if($question->answer == NULL)
                Ожидает ответа
            @elseif($question->status == 0)
                Скрыт
            @else 
                Опубликован            
            @endif
        </td>
        <td>{{$question->question}}</td>        
        <td>           
            <a class="btn btn-primary" href="{{ route('question.edit', $question) }}">Редактировать</a>
        </td>
        <td>
            <a class="btn btn-primary" href="{{ route('publishHide.questions', $question) }}">{{$question->status == 0 ? 'Опубликовать' : 'Скрыть'}}</a>
        </td>        
        <td>
            <form action="{{ route('question.destroy', $question) }}" method="post">
                <input class="btn btn-primary" type="submit" value="Удалить вопрос">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
            </form>
        </td>        
    </tr>    
    @endforeach
</table>
<span>{{$questions->links()}}</span>
<a class="admin" href="{{ route('category.index') }}">Назад к категориям</a>
<a class="admin" href="{{ route('admin.home') }}">Вернуться к списку возможностей администратора</a>
@endsection